{{- if .Values.certificate.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "web-streaming-example.fullname" . }}
  labels:
    {{- include "web-streaming-example.labels" . | nindent 4 }}
spec:
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    - {{ .host }}:3180
    {{- end }}
  secretName: {{ include "web-streaming-example.fullname" . }}
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
{{- end }}
