apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web-streaming-example.fullname" . }}
  labels:
    {{- include "web-streaming-example.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.persistence.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}