apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-streaming-example.fullname" . }}
  labels:
    {{- include "web-streaming-example.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.backend }}
      targetPort: {{ .Values.service.ports.backend }}
      protocol: TCP
      name: backend
    - port: {{ .Values.service.ports.web }}
      targetPort: {{ .Values.service.ports.web }}
      protocol: TCP
      name: web
  selector:
    {{- include "web-streaming-example.selectorLabels" . | nindent 4 }}
