# Default values for web-streaming-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  backend:
    repository: "ovc-sample-registry:42607/web-streaming-example/backend"
    pullPolicy: Always
    tag: "latest"
  web:
    repository: "ovc-sample-registry:42607/web-streaming-example/web"
    pullPolicy: Always
    tag: "latest"

nvcf:
  # The service API key generated on the NGC portal
  key: ""

  # The endpoint used by the backend to talk to NVCF API
  controlEndpoint: "https://api.nvcf.nvidia.com"

  # The endpoint used by the backend to connect to NVCF functions with WebSockets
  signalingEndpoint: "wss://grpc.nvcf.nvidia.com"

  # Number of seconds to cache data pulled from NVCF API
  cacheTtl: 300

config:
  auth:
    # Client ID of your application provided by the IdP
    clientId: ""

    # The Customer Web App URL where the IdP must redirect the user back.
    # This is the URL used for the example. Must end with /openid
    redirectUri: "https://ovc-sample:3180/openid"

    # The identity provider URL (where users will be redirected for authentication)
    authority: ""

    # The endpoint used to retrieve OpenID Connect configuration from the identity provider.
    # https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
    metadataUri: ""

    # The algorithm used by the IdP to generate ID tokens
    jwksAlg: "ES256"

    # Number of seconds to cache public keys (JWK) retrieved from jwks_uri.
    # Usually this default value doesn't need to be changed.
    # Check your IDP docs though regarding the recommended time the client should cache the public keys (JWK) for.
    jwksTtl: 300

    # Number of seconds to cache user info retrieved from userinfo_endpoint.
    # Usually this default value doesn't need to be changed.
    userinfoTtl: 300

    # Scopes that define information required from the identity provider
    scope: "openid profile email"

    # The group ID that user must be a member of to update the database.
    # Verified by checking the user ID token and calling /userinfo endpoint.
    adminGroup: "admin"

    # Defines what field in the token should be used for checking user groups.
    groupsClaim: "groups"

  endpoints:
    backend: "https://ovc-sample:3180/api"
    nucleus: ""

  # Maximum session duration in seconds before users get disconnected.
  sessionTtl: 28800

  # Defines when the user should see the notification about the ending session (in seconds).
  sessionEndNotificationTime: 600

  # Defines for how long the session end notification should be displayed (in seconds).
  sessionEndNotificationDuration: 30

  # Defines how often (in seconds) the service checks for session aliveness (timeouts and idle state).
  sessionWatchInterval: 60

  # Number of seconds before idle sessions are stopped.
  # You MUST make sure the value matches the timeout you specified during the NVCF function creation.
  # Only one global timeout is supported on the portal side,
  # therefore all NVCF functions should be created with the same session resume timeout matching the value below.
  # The specified value must be less or equal 300 seconds (5 minutes) which is the maximum NVCF session reconnect timeout.
  sessionIdleTimeout: 300

  # Maximum amount of allowed running sessions for each user per application
  maxAppInstancesCount: 3

  # Defines Content-Security-Policy for the web frontend
  csp: ""

  # Extra environment variables to be passed to the backend container
  # Useful for OpenTelemetry configuration and other custom environment variables
  extraVars: {}
    # Example OpenTelemetry environment variables:
    # OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    # OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    # OTEL_RESOURCE_ATTRIBUTES: "service.name=web-streaming-example,service.version=1.0.0"
    # OTEL_TRACES_EXPORTER: "otlp"
    # OTEL_METRICS_EXPORTER: "otlp"
    # OTEL_LOGS_EXPORTER: "otlp"

  # Maximum size of incomplete HTTP events (headers) in bytes for HTTP1.1. Default is 16KB.
  # Increase this value if you have headers that exceed the default limit.
  h11MaxIncompleteEventSize: 16384

apiKeys:
  # Whether to enable API key authentication
  enabled: false
  # API keys configuration
  keys: []
    # - name: "admin-service"
    #   value: "api-key-admin-1234567890abcdef"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101

securityContext:
  backend:
    runAsUser: 101
    runAsGroup: 101
  web:
    runAsUser: 101
    runAsGroup: 101

service:
  type: ClusterIP
  annotations: {}
  ports:
    web: 8080
    backend: 8000

ingress:
  enabled: true
  className: ""
  annotations:
    # Handle large headers/cookies at ingress level
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "128k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8 128k"
  hosts:
    - host: ovc-sample
  tls:
    - secretName: web-streaming-example
      hosts:
        - ovc-sample

certificate:
  create: true

clusterIssuer:
  create: true


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

persistence:
  accessModes:
    - ReadWriteOnce
  size: 1G
  storageClass: ""
  keep: true

nodeSelector: {}

tolerations: []

affinity: {}
